import '../styles/globals.css';
import styles from '../styles/Layout.module.css';
import Provider from '@/components/Providers';


export const metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <Provider session={session}>
        <body className='h-screen'>
          <div className='flex py-[20px] bg-blue-400'>
            <div className='m-auto bg-slate-50 rounded-md w-4/5 h-3/4 grid lg:grid-cols-2'>
              <div className={styles.imgStyle}>
                <div className={styles.cartoonImg}></div>
                <div className={styles.cloud_one}></div>
                <div className={styles.cloud_two}></div>
              </div>
              <div className='right flex flex-col justify-evenly'>
                <div className='text-center py-10'>
                    {children}
                </div>
              </div>
            </div>
          </div>
        </body>
      </Provider>
    </html>
  )
}
